### Create a user
POST http://localhost:3000/users
Content-Type: application/json

{
  "gender": "Male",
  "firstName": "John",
  "lastName": "Doe",
  "username": "johndoe",
  "password": "password123",
  "email": "john.doe@example.com",
  "role": "USER",
  "status": "ACTIVE",
  "address": {
    "street": "Main Street",
    "number": 123,
    "zip": 1010,
    "city": "Vienna",
    "country": "Austria"
  },
  "paymentMethod": {
    "name": "Credit Card"
  }
}

### Retrieve all payment methods
GET http://localhost:3000/paymentMethods

### Create a flight
POST http://localhost:3000/flights
Content-Type: application/json

{
  "flightNumber": "LH1234",
  "departureTime": "2024-11-09T15:00:00+02:00",
  "arrivalTime": "2024-11-09T19:30:00+02:00",
  "flightOrigin": {
    "airportCode": "JFK",
    "airportText": "John F. Kennedy International Airport"
  },
  "flightDestination": {
    "airportCode": "LAX",
    "airportText": "Los Angeles International Airport"
  },
  "aircraft": {
    "serialNumber": "A123456789",
    "manufacturer": "Boeing",
    "model": "767-300ER",
    "capacity": 211,
    "airline": {
      "name": "Austrian Airlines"
    }
  }
}


### create a baggage type
POST http://localhost:3000/baggageTypes
Content-Type: application/json

{
  "name": "carry-on luggage",
  "fee": 15.00
}


### Create a Booking
POST http://localhost:3000/bookings
Content-Type: application/json

{
  "status": "Confirmed",
  "price": 250.00,
  "bookingDate": "2024-11-11T14:30:00",
  "userId": "3233398c-561d-4b15-ba59-cf0e8980f61e",
  "paymentMethodId": "2165478d-80db-4fb3-93f2-70dd348ac2d8",
  "flightId": "c86f3ffb-a656-4215-9cf7-073f28824c58",
  "passengers": [
    {
      "firstName": "Alice",
      "lastName": "Smith",
      "birthday": "1990-05-15",
      "seatNumber": "",
      "baggage": {
        "baggageTypeId": "ce73e1e7-a6a8-436b-a40d-bcf7e1f410b1"
      }
    },
    {
      "firstName": "Bob",
      "lastName": "Johnson",
      "birthday": "1985-08-22",
      "seatNumber": "",
      "baggage": {
        "baggageTypeId": "ce73e1e7-a6a8-436b-a40d-bcf7e1f410b1"
      }
    },
    {
      "firstName": "Charlie",
      "lastName": "Brown",
      "birthday": "1992-02-10",
      "seatNumber": "",
      "baggage": {
        "baggageTypeId": "ce73e1e7-a6a8-436b-a40d-bcf7e1f410b1"
      }
    }
  ]
}


### get all bookings
GET http://localhost:3000/bookings

### get booking by id
GET http://localhost:3000/bookings/33d9f4f1-869f-4b43-a9e4-e3bea193b527

### delete booking by id
DELETE http://localhost:3000/bookings/33d9f4f1-869f-4b43-a9e4-e3bea193b527

