### Create a user
POST http://localhost:3000/users
Content-Type: application/json

{
  "gender": "Male",
  "firstName": "John",
  "lastName": "Doe",
  "username": "johndoe",
  "password": "password123",
  "email": "john.doe@example.com",
  "role": "USER",
  "status": "ACTIVE",
  "address": {
    "street": "Main Street",
    "number": 123,
    "zip": 1010,
    "city": "Vienna",
    "country": "Austria"
  },
  "paymentMethod": {
    "name": "Credit Card"
  }
}

### Retrieve all payment methods
GET http://localhost:3000/paymentMethods

### Create a flight
POST http://localhost:3000/flights
Content-Type: application/json

{
  "flightNumber": "LH1234",
  "departureTime": "2024-11-09T15:00:00+02:00",
  "arrivalTime": "2024-11-09T19:30:00+02:00",
  "flightOrigin": {
    "airportCode": "JFK",
    "airportText": "John F. Kennedy International Airport"
  },
  "flightDestination": {
    "airportCode": "LAX",
    "airportText": "Los Angeles International Airport"
  },
  "aircraft": {
    "serialNumber": "A123456789",
    "manufacturer": "Boeing",
    "model": "767-300ER",
    "capacity": 211,
    "airline": {
      "name": "Austrian Airlines"
    }
  }
}


### create a baggage type
POST http://localhost:3000/baggageTypes
Content-Type: application/json

{
  "name": "carry-on luggage",
  "fee": 15.00
}

### get all baggages
GET http://localhost:3000/baggages



### Create a Booking
POST http://localhost:3000/bookings
Content-Type: application/json

{
  "status": "Confirmed",
  "price": 250.00,
  "bookingDate": "2024-11-11T14:30:00",
  "userId": "a27ed6be-27ec-4584-ae8a-8a74a7b91c4c",
  "paymentMethodId": "ce457968-b397-49d6-aa16-d2ff587c21bb",
  "flightId": "95a7244b-0e71-40f4-ab0f-179f430ecf4d",
  "passengers": [
    {
      "firstName": "Alice",
      "lastName": "Smith",
      "birthday": "1990-05-15",
      "seatNumber": "",
      "baggage": {
        "baggageTypeId": "d5d45372-bbb1-44ee-9a00-1ba206a6fcb7"
      }
    },
    {
      "firstName": "Bob",
      "lastName": "Johnson",
      "birthday": "1985-08-22",
      "seatNumber": "",
      "baggage": {
        "baggageTypeId": "d5d45372-bbb1-44ee-9a00-1ba206a6fcb7"
      }
    },
    {
      "firstName": "Charlie",
      "lastName": "Brown",
      "birthday": "1992-02-10",
      "seatNumber": "",
      "baggage": {
        "baggageTypeId": "d5d45372-bbb1-44ee-9a00-1ba206a6fcb7"
      }
    }
  ]
}


### get all bookings
GET http://localhost:3000/bookings

### get booking by id
GET http://localhost:3000/bookings/d3dc2e53-fc07-49a1-a0f3-820ab66f8e11

### delete booking by id
DELETE http://localhost:3000/bookings/d3dc2e53-fc07-49a1-a0f3-820ab66f8e11

