### Create an airline
POST http://localhost:3000/airlines
Content-Type: application/json

{
  "name": "Austrian Airlines"
}

### Create an airline
POST http://localhost:3000/airlines
Content-Type: application/json

{
  "name": "Air France"
}

### Retrieve all airlines
GET http://localhost:3000/airlines

### Create an aircraft
POST http://localhost:3000/aircrafts
Content-Type: application/json

{
  "serialNumber": "A2",
  "manufacturer": "Boeing",
  "model": "787-9",
  "capacity": 294,
  "airline": {
    "name": "Austrian Airlines"
  }
}

### Retrieve all aircrafts
GET http://localhost:3000/aircrafts

### Create a payment method
POST http://localhost:3000/paymentMethods
Content-Type: application/json

{
  "name": "Credit Card"
}

### Create a payment method
POST http://localhost:3000/paymentMethods
Content-Type: application/json

{
  "name": "PayPal"
}

### Retreive all payment methods
GET http://localhost:3000/paymentMethods

### Create a user
POST http://localhost:3000/users
Content-Type: application/json

{
  "gender": "Male",
  "firstName": "John",
  "lastName": "Doe",
  "username": "john_doe",
  "password": "securepassword",
  "email": "john.doe@example.com",
  "role": "USER",
  "status": "ACTIVE",
  "address": {
    "street": "Main St",
    "number": 123,
    "zip": 12345,
    "city": "Springfield",
    "country": "USA"
  },
  "paymentMethod": {
    "name": "Credit Card"
  }
}

### Create a user
POST http://localhost:3000/users
Content-Type: application/json

{
  "gender": "Female",
  "firstName": "Jane",
  "lastName": "Smith",
  "username": "jane_smith",
  "password": "anotherpassword",
  "email": "jane.smith@example.com",
  "role": "USER",
  "status": "ACTIVE",
  "address": {
    "street": "Oak St",
    "number": 456,
    "zip": 54321,
    "city": "Greenfield",
    "country": "USA"
  },
  "paymentMethod": {
    "name": "PayPal"
  }
}

### Retreive all users
GET http://localhost:3000/users
