###
POST http://localhost:3000/flights
Content-Type: application/json

{
  "flightNumber": "LH12345",
  "departureTime": "2024-11-03T15:30:00",
  "arrivalTime": "2024-11-03T18:45:00",
  "flightOrigin": {
    "airportCode": "JFK",
    "airportText": "John F. Kennedy International Airport"
  },
  "flightDestination": {
    "airportCode": "LAX",
    "airportText": "Los Angeles International Airport"
  },
  "aircraft": {
    "serialNumber": "A123456789",
    "manufacturer": "Boeing",
    "model": "767-300ER",
    "capacity": 211,
    "airline": {
      "name": "Austrian Airlines"
    }
  }
}

###
POST http://localhost:3000/airports
Content-Type: application/json

{
  "airportCode": "LAX",
  "airportText": "Los Angeles International Airport"
}

###
POST http://localhost:3000/airports
Content-Type: application/json

{
  "airportCode": "JFK",
  "airportText": "John F. Kennedy International Airport"
}

###
GET http://localhost:3000/airports


###
POST http://localhost:3000/airlines
Content-Type: application/json

{
  "name": "Austrian Airlines"
}

###
POST http://localhost:3000/airlines
Content-Type: application/json

{
  "name": "Air France"
}

###
GET http://localhost:3000/airlines

###
POST http://localhost:3000/aircrafts
Content-Type: application/json

{
  "serialNumber": "A2",
  "manufacturer": "Boeing",
  "model": "787-9",
  "capacity": 294,
  "airline": {
    "name": "Austrian Airlines"
  }
}

###
GET http://localhost:3000/aircrafts

###
POST http://localhost:3000/paymentMethods
Content-Type: application/json

{
  "name": "Credit Card"
}

###
POST http://localhost:3000/paymentMethods
Content-Type: application/json

{
  "name": "PayPal"
}

###
GET http://localhost:3000/paymentMethods

###
POST http://localhost:3000/users
Content-Type: application/json

{
  "gender": "Male",
  "firstName": "John",
  "lastName": "Doe",
  "username": "john_doe",
  "password": "securepassword",
  "email": "john.doe@example.com",
  "role": "USER",
  "status": "ACTIVE",
  "address": {
    "street": "Main St",
    "number": 123,
    "zip": 12345,
    "city": "Springfield",
    "country": "USA"
  },
  "paymentMethod": {
    "name": "Credit Card"
  }
}

###
POST http://localhost:3000/users
Content-Type: application/json

{
  "gender": "Female",
  "firstName": "Jane",
  "lastName": "Smith",
  "username": "jane_smith",
  "password": "anotherpassword",
  "email": "jane.smith@example.com",
  "role": "USER",
  "status": "ACTIVE",
  "address": {
    "street": "Oak St",
    "number": 456,
    "zip": 54321,
    "city": "Greenfield",
    "country": "USA"
  },
  "paymentMethod": {
    "name": "PayPal"
  }
}

###
GET http://localhost:3000/users
