###
POST http://localhost:8080/flights
Content-Type: application/json

{
  "flightNumber": "LH12345",
  "departureTime": "2024-11-03T15:30:00",
  "arrivalTime": "2024-11-03T18:45:00",
  "flightOrigin": {
    "airportCode": "JFK",
    "airportText": "John F. Kennedy International Airport"
  },
  "flightDestination": {
    "airportCode": "LAX",
    "airportText": "Los Angeles International Airport"
  },
  "aircraft": {
    "serialNumber": "A123456789",
    "manufacturer": "Boeing",
    "model": "767-300ER",
    "capacity": 211,
    "airline": {
      "name": "Austrian Airlines"
    }
  }
}

###
POST http://localhost:8080/airports
Content-Type: application/json

{
  "airportCode": "LAX",
  "airportText": "Los Angeles International Airport"
}

###
POST http://localhost:8080/airports
Content-Type: application/json

{
  "airportCode": "JFK",
  "airportText": "John F. Kennedy International Airport"
}

###
GET http://localhost:8080/airports


###
POST http://localhost:8080/airlines
Content-Type: application/json

{
  "name": "Austrian Airlines"
}

###
POST http://localhost:8080/airlines
Content-Type: application/json

{
  "name": "Air France"
}

###
GET http://localhost:8080/airlines

###
POST http://localhost:8080/aircrafts
Content-Type: application/json

{
  "serialNumber": "A2",
  "manufacturer": "Boeing",
  "model": "787-9",
  "capacity": 294,
  "airline": {
    "name": "Austrian Airlines"
  }
}

###
GET http://localhost:8080/aircrafts

