### Create a new passenger
POST http://localhost:3000/passengers
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "birthday": "1980-01-01",
  "seatNumber": "12A",
  "baggage": {
    "baggageTypeId": "e60eb5aa-2ca3-4a14-94f8-e09a804d69cd"
  }
}

### Retrieve all passengers
GET http://localhost:3000/passengers

### Retrieve a passenger by ID
GET http://localhost:3000/passengers/1dfad342-6a15-412f-a944-952dff3cdf36

### Update an existing passenger
PUT http://localhost:3000/passengers/83ae6d2f-cda9-4bab-8b82-324777f492f1
Content-Type: application/json

{
  "firstName": "Jane",
  "lastName": "Doe",
  "birthday": "1985-05-15",
  "seatNumber": "14B",
  "baggage": {
    "baggageTypeId": "e60eb5aa-2ca3-4a14-94f8-e09a804d69cd"
  }
}

### Delete a passenger by ID
DELETE http://localhost:3000/passengers/474e4928-aa1a-45f5-952f-b30fb0a55da4
